### ISSUE TITLE
[BUG]显示无法连接数据库怎么解决呀😭

### ISSUE THREAD

**Issue by likang295085** [Clansty/Icalingua#212]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Clansty** [comment]
@likang295085 请描述你的问题

**Comment by likang295085** [comment]
好的

**Comment by likang295085** [comment]
> @likang295085 请描述你的问题

![Screenshot 2021-09-03 14 00 16](https://user-images.githubusercontent.com/48517143/131957719-2c0eaf05-b6e2-41a9-8888-0c9cc053f386.png)
就是这样子呀😭

**Comment by Clansty** [comment]
@likang295085 没有什么提示吗

**Comment by Clansty** [comment]
@likang295085 如果没有提示的话，点击上面的开发者工具按钮看看控制台里有没有报错

**Comment by likang295085** [comment]
![Screenshot 2021-09-03 14 01 28](https://user-images.githubusercontent.com/48517143/131957886-20a9fa56-46cc-4f5b-a2f3-c0914899f567.png)
有提示的刚刚没截图到

**Comment by likang295085** [comment]
好的

**Comment by Clansty** [comment]
请打开一个终端

- 如果你使用 `.pkg.tar.zst` 格式安装包，请输入 `icalingua` 回车
- 如果你使用 `.rpm` 或 `.deb` 格式安装包，请输入 `/opt/Icalingua/icalingua` 回车
- 如果你使用 AppImage 或者 `tar.xz` 包，请将执行文件拖入终端回车

然后正常登录，并附上终端里的输出

**Comment by likang295085** [comment]
> 请打开一个终端
> 
> * 如果你使用 `.pkg.tar.zst` 格式安装包，请输入 `icalingua` 回车
> * 如果你使用 `.rpm` 或 `.deb` 格式安装包，请输入 `/opt/Icalingua/icalingua` 回车
> * 如果你使用 AppImage 或者 `tar.xz` 包，请将执行文件拖入终端回车
> 
> 然后正常登录，并附上终端里的输出

嗯嗯，谢谢哩

**Comment by likang295085** [comment]
> 请打开一个终端
> 
> * 如果你使用 `.pkg.tar.zst` 格式安装包，请输入 `icalingua` 回车
> * 如果你使用 `.rpm` 或 `.deb` 格式安装包，请输入 `/opt/Icalingua/icalingua` 回车
> * 如果你使用 AppImage 或者 `tar.xz` 包，请将执行文件拖入终端回车
> 
> 然后正常登录，并附上终端里的输出

我换了一个storage engine后成功登录呢😂

**Comment by Clansty** [comment]
> > 请打开一个终端
> > 
> > * 如果你使用 `.pkg.tar.zst` 格式安装包，请输入 `icalingua` 回车
> > * 如果你使用 `.rpm` 或 `.deb` 格式安装包，请输入 `/opt/Icalingua/icalingua` 回车
> > * 如果你使用 AppImage 或者 `tar.xz` 包，请将执行文件拖入终端回车
> > 
> > 然后正常登录，并附上终端里的输出
> 
> 我换了一个storage engine后成功登录了joy

不应该啊，别的 engine 需要另外安装运行数据库服务器的

**Comment by lixiang810** [comment]
请到~/.config/Icalingua/crash-reports文件夹，把里面的错误信息发出来。

**Comment by IMxingyus** [comment]
> 请到~/.config/Icalingua/crash-reports文件夹，把里面的错误信息发出来。

如果没猜错的话，他应该是在ChromeOS上面运行。我也遇到了同样的错误。这是log文件
{"message":{"errname":"Error","errMsg":"connect ECONNREFUSED 127.0.0.1:3306","e":"Error: connect ECONNREFUSED 127.0.0.1:3306"},"level":"error","service":"eqq-service"}
{"message":{"errname":"Error","errMsg":"Request failed with status code 500","e":"Error: Request failed with status code 500"},"level":"error","service":"eqq-service"}

另外，这是终端的输出
user@penguin:~$ /opt/Icalingua/icalingua
[1415:0927/064336.342560:ERROR:viz_main_impl.cc(162)] Exiting GPU process due to errors during initialization
[1431:0927/064336.616825:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
Cannot find an external image viewer
Cannot find an external media player
icalingua> (node:1385) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(Use `icalingua --trace-warnings ...` to show where the warning was created)
(node:1385) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
Knex: run
$ npm install sqlite3 --save
/lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.4BMoEP)
Error: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.4BMoEP)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1143:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Module._load (internal/modules/cjs/loader.js:781:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/Icalingua/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1083:30)
Error: Knex: run
$ npm install sqlite3 --save
/lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.4BMoEP)
    at Client_SQLite3.initializeDriver (/opt/Icalingua/resources/app.asar/node_modules/knex/lib/client.js:182:13)
    at new Client (/opt/Icalingua/resources/app.asar/node_modules/knex/lib/client.js:71:12)
    at new Client_SQLite3 (/opt/Icalingua/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:20:5)
    at Object.knex [as default] (/opt/Icalingua/resources/app.asar/node_modules/knex/lib/knex-builder/Knex.js:12:28)
    at new e (/opt/Icalingua/resources/app.asar/dist/electron/main.js:35:81185)
    at /opt/Icalingua/resources/app.asar/dist/electron/main.js:1:187455
    at /opt/Icalingua/resources/app.asar/dist/electron/main.js:1:175134
    at Object.next (/opt/Icalingua/resources/app.asar/dist/electron/main.js:1:175239)
    at /opt/Icalingua/resources/app.asar/dist/electron/main.js:1:174151
    at new Promise (<anonymous>)

希望能够适配ChromeOS

**Comment by lixiang810** [comment]
@IMxingyus 懂了，没把 sqlite 打包进去。
你是 AppImage 吗？

**Comment by lixiang810** [comment]
（而且楼主说了是 debian，不是 chrome os。按道理 chrome os 装腾讯官方的移动 app 就好，腾讯已经做了的事情，我们不是太想做。

**Comment by Clansty** [comment]
另外 chrome OS 不是内置 Debian嘛

**Comment by IMxingyus** [comment]
> @IMxingyus懂了，没把 sqlite 包装进去。
> 你是 AppImage 吗？

不，我用的deb

**Comment by zhanghua000** [comment]
也许是数据库设置了身份认证？我这里把 MongoDB 设置了身份验证后也出现了无法连接数据库的问题。

**Comment by lixiang810** [comment]
数据库是啥

**Comment by lixiang810** [comment]
@IMxingyus 电脑里装 Redis 了吗？

**Comment by lixiang810** [comment]
@IMxingyus 那你为什么选的redis？

**Comment by wuyueshiwo** [comment]
哈哈，我也是mysql的连不上，我mysql是用docker起的，然后换成docker启动的redis就可以了
