### ISSUE TITLE
[BUG] 启动时自动连接Aria2 失败

### ISSUE THREAD

**Issue by sukanka** [Clansty/Icalingua#213]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
应用启动时连接 aria2 会失败，但是启动后手动在 **选项>Aria2 下载管理器设置** 里面点击 **保存**，就能够连得上。

**To Reproduce / 复现过程**
启动 Icalingua, 尝试下载一个文件会失败

**Expected behavior / 预期的结果**
启动时 自动连接上 Aria2

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
```
➜  ~ icalingua 
icalingua> (node:456540) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure bydisabling certificate verification.
(Use `electron --trace-warnings ...` to show where the warning was created)
Aria2 failed a {
target: T {
_events: [Object: null prototype] {
close: [Function],
message: [Function],
open: [Function],
error: [Function]
},
_eventsCount: 4,
_maxListeners: undefined,
_binaryType: 'nodebuffer',
_closeCode: 1006,
_closeFrameReceived: false,
_closeFrameSent: false,
_closeMessage: '',
_closeTimer: null,
_extensions: {},
_protocol: '',
_readyState: 3,
_receiver: null,
_sender: null,
_socket: null,
_bufferedAmount: 0,
_isServer: false,
_redirects: 0,
_url: 'wss://localhost:6800/jsonrpc',
_req: null,
[Symbol(kCapture)]: false
},
type: 'error',
message: 'unable to verify the first certificate',
error: Error: unable to verify the first certificate
at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
at TLSSocket.emit (events.js:315:20)
at TLSSocket.EventEmitter.emit (domain.js:467:12)
at TLSSocket._finishInit (_tls_wrap.js:932:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
at TLSWrap.callbackTrampoline (internal/async_hooks.js:131:14) {
code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
}
(node:456540) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
```
手动连接后
```
Aria2 RPC connected
```
**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]
 ```
electron 13.2.3-1
icalingua 2.2.1-1
```

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

我的 Aria2 开启了 secure,配置了本地证书。
![Screenshot_20210903_185921](https://user-images.githubusercontent.com/31362108/131995168-00ee748f-1732-4a04-b6eb-45145dae2b4a.png)

**Comment by sukanka** [comment]
Fixed in [release v2.3.2](https://github.com/Icalingua/Icalingua/releases/tag/v2.3.2).
