### ISSUE TITLE
Aria2 启用 secure 时连接失败

### ISSUE THREAD

**Issue by sukanka** [Clansty/Icalingua#80]
## 问题描述
在 `1.5.7` (不含)以后的 electron-qq 版本中,无法连接  `aria2`,无论是否启用 `secure` 选项,都无法连接,提示 `Aria2 failed`.

我的 `aria2.conf` (部分)
```
# 是否启用 RPC 服务的 SSL/TLS 加密,
# 启用加密后 RPC 服务需要使用 https 或者 wss 协议连接
rpc-secure=true
# 在 RPC 服务中启用 SSL/TLS 加密时的证书文件,
# 使用 PEM 格式时，您必须通过 --rpc-private-key 指定私钥
rpc-certificate=/home/sukanka/.local/share/mkcert/localhost.pem
# 在 RPC 服务中启用 SSL/TLS 加密时的私钥文件
rpc-private-key=/home/sukanka/.local/share/mkcert/localhost-key.pem
```
## 报错输出
```
┏ Electron -------------------

  Aria2 failed ErrorEvent {
    target: WebSocket {
      _events: [Object: null prototype] {
        close: [Function],
        message: [Function],
        open: [Function],
        error: [Function]
      },
      _eventsCount: 4,
      _maxListeners: undefined,
      _binaryType: 'nodebuffer',
      _closeCode: 1006,
      _closeFrameReceived: false,
      _closeFrameSent: false,
      _closeMessage: '',
      _closeTimer: null,
      _extensions: {},
      _protocol: '',
      _readyState: 3,
      _receiver: null,
      _sender: null,
      _socket: null,
      _bufferedAmount: 0,
      _isServer: false,
      _redirects: 0,
      _url: 'wss://localhost:6800/jsonrpc',
      _req: null,
      [Symbol(kCapture)]: false
    },
    type: 'error',
    message: 'unable to verify the first certificate',
    error: Error: unable to verify the first certificate
        at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
        at TLSSocket.emit (events.js:315:20)
        at TLSSocket._finishInit (_tls_wrap.js:932:8)
        at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
      code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
    }
  }
  
┗ ----------------------------
```
## 解决方案
1. 在 `aria2.conf` 将 `rpc-secure` 设置为 `false` 并且在 electron-qq 中关闭 `secure` (但是我的 [ariaNg](https://aria.sukanka.com/#!/downloading) 就无法连接,因为网页启用了 `https`).
2. 谷歌搜索关键词 `unable to verify the first certificate` 发现另一种解决方案设置环境变量 `NODE_TLS_REJECT_UNAUTHORIZED=0` 再运行 electron-qq

**Comment by Clansty** [comment]
下个版本应该修复了
